# Generated by Django 2.2.6 on 2019-10-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_count_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('externOnly', models.DateTimeField()),
                ('location', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
