# Generated by Django 2.2.6 on 2019-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='externOnly',
            field=models.BooleanField(),
        ),
    ]
