# Generated by Django 2.2.6 on 2019-10-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191021_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='externOnly',
            new_name='extern_only',
        ),
        migrations.AddField(
            model_name='event',
            name='color_background',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='color_icon',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
