# Generated by Django 2.2.6 on 2019-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191023_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color_background',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='color_icon',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
