# Generated by Django 2.2.6 on 2019-11-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_game_genre_image_mood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.Mood'),
        ),
        migrations.AlterField(
            model_name='game',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.Type'),
        ),
    ]
