# Generated by Django 2.2.6 on 2019-11-21 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191102_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games_favorite',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.Game'),
        ),
        migrations.CreateModel(
            name='SuggestionGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
