# Generated by Django 2.2.6 on 2019-11-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191121_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='filters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
